### ISSUE TITLE
Add processor for side effects and indications in SIDER

### ISSUE THREAD

**Issue by cthoyt** [bgyori/indra_cogex#41]
The [Side Effect Resource](http://sideeffects.embl.de/) might be aging, but it still has really interesting stuff in it and has been a huge part of successful efforts like Hetionet. Unfortunately, it uses vocabularies like STITCH (which can luckily be trivially converted to pubchem.compound), UMLS and MEDDRA, so we'll have to see how good the INDRA BioOntology is at standardizing away from those

Related processors:
- https://github.com/bio2bel/sider
- https://github.com/dhimmel/SIDER4

**Comment by bgyori** [comment]
Done in #40
