### ISSUE TITLE
Issue normalizing GO terms

### ISSUE THREAD

**Issue by cthoyt** [bgyori/indra_cogex#51]
The following code currently fails, meaning that I can't run a proper query for HGNC genes for this GO term. Looking into it now...
```python
from indra_cogex.representation import norm_id

assert norm_id("GO", "0032571") == "go:0032571"
```

**Comment by bgyori** [comment]
I think the expected input is
```
norm_id("GO", "GO:0032571")
```
Here the namespace and ID have to correspond to valid INDRA values hence the above.

**Comment by cthoyt** [comment]
either way what comes out is `"go:2571"`, totally crazy

**Comment by cthoyt** [comment]
oh sorry, I misread that. I will check if I fix the input

**Comment by cthoyt** [comment]
False alarm! perhaps the normalize function should yell if it gets something unexpected?

**Comment by bgyori** [comment]
That's just because 3 characters corresponding to "GO:" are stripped off by index since the code recognizes that this is a "namespace embedded in ID" situation, which is why this weirdness happens if the embedded prefix is missing.
